AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Function1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Function1
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Architectures: 
        - arm64
      CodeUri: lambdas/lambda_inventaria_alerts/
      Role: arn:aws:iam::307154673918:role/lambda-execution-role
      Timeout: 900
      Layers:
        - arn:aws:lambda:us-east-1:307154673918:layer:psycopg2-layer:1
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39-Arm64:25
      Events:
        ScheduleTrigger:
          Type: Schedule
          Properties:
            Schedule: "cron(0 7 * * ? *)"
  Function2:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_bsale_fetch_movements
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Architectures: 
        - arm64
      CodeUri: lambdas/lambda_bsale_fetch_movements/
      Role: arn:aws:iam::307154673918:role/lambda-execution-role
      Timeout: 900
      Layers:
        - arn:aws:lambda:us-east-1:307154673918:layer:psycopg2-layer:1
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39-Arm64:25
      Events:
        ScheduleTrigger:
          Type: Schedule
          Properties:
            Schedule: "cron(0 6 * * ? *)"
  Function3:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_bsale_fetch_products
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Architectures: 
        - arm64
      CodeUri: lambdas/lambda_bsale_fetch_products/
      Role: arn:aws:iam::307154673918:role/lambda-execution-role
      Timeout: 900
      Layers:
        - arn:aws:lambda:us-east-1:307154673918:layer:psycopg2-layer:1
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39-Arm64:25
      Events:
        ScheduleTrigger:
          Type: Schedule
          Properties:
            Schedule: "cron(0 3 ? * 1 *)"
