AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Function1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function1.app.lambda_handler
      Runtime: python3.9
      CodeUri: lambdas/function1/
      Role: arn:aws:iam::123456789012:role/lambda-execution-role
  Function2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function2.app.lambda_handler
      Runtime: python3.9
      CodeUri: lambdas/function2/
      Role: arn:aws:iam::123456789012:role/lambda-execution-role
