AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Function1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function1.lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: lambdas/function1/
      Role: arn:aws:iam::307154673918:role/lambda-execution-role
      Timeout: 900
      Layers:
        - arn:aws:lambda:us-east-1:307154673918:layer:psycopg2-layer:1
      Events:
        ScheduleTrigger:
          Type: Schedule
          Properties:
            Schedule: "cron(0 6 * * ? *)"
  Function2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function2.app.lambda_handler
      Runtime: python3.9
      CodeUri: lambdas/function2/
      Role: arn:aws:iam::307154673918:role/lambda-execution-role
