name: Deploy Lambdas to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install AWS SAM CLI
      run: |
        curl -sL https://github.com/aws/aws-sam-cli/releases/download/v1.77.0/aws-sam-cli-linux-x86_64.zip -o sam-cli.zip
        unzip sam-cli.zip -d sam-cli
        sudo ./sam-cli/install --update

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build SAM Application
      run: sam build

    - name: Deploy to AWS
      run: |
        sam deploy \
          --no-fail-on-empty-changeset \
          --template-file .aws-sam/build/template.yaml \
          --stack-name inventaria-lambda-stack \
          --s3-bucket inventaria-sam-artifacts \
          --capabilities CAPABILITY_IAM

